
4581352 = 12 # Onule
6209658 = 3 # ShizCalev
12817816 = 1 # ZephyrTFA
28007787 = 3 # sqnztb
33048583 = 3 # Zytolg
43283559 = 3 # SandPoot
44090982 = 15 # prodirus
53777086 = 14 # JohnFulpWillard
58045821 = 3 # GoldenAlpharex
70232195 = 582 # Jolly-66
82386923 = 1 # Paxilmaniac
101908892 = 5755 # TaleStationBot
105393050 = 0 # SpaceSmithers