
12817816 = 1 # ZephyrTFA
28007787 = 3 # sqnztb
43283559 = 3 # SandPoot
44090982 = 9 # prodirus
53777086 = 11 # JohnFulpWillard
58045821 = 3 # GoldenAlpharex
70232195 = 83 # Jolly-66
101908892 = 72 # TaleStationBot